# Generated by Django 5.1.2 on 2024-11-18 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_id', models.TextField()),
                ('img', models.FileField(upload_to='')),
                ('dis', models.TextField()),
            ],
        ),
    ]
