# Generated by Django 5.1.2 on 2024-11-27 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('image', models.FileField(upload_to='')),
                ('dis', models.TextField()),
                ('overview', models.TextField()),
                ('topic', models.TextField()),
                ('batch', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Course',
        ),
    ]
